## WEEKTAAK 3
while True:
    data = input("Wat is de sequentie ")
    alles = len(data)
    a = data.count("A")
    t = data.count("T")
    g = data.count("G")
    c = data.count("C")
    n = data.count("N")
    atgcn = a+t+g+c+n #Telt alle basen bij elkaar op

    if atgcn == alles: #Als het er in de basen geen andere tekens zitten dan ATGCN dan zegt hij dat het DNA is
        print("Het is RNA")
        print("Totaal A ",a)
        print("Totaal T ",t)
        print("Totaal G ",g)
        print("Totaal C ",c)
        print("Totaal N ",n)
        print ("Totaal van de sequentie ",alles)
    else: #Anders is het een eiwit
        print("Het is een eiwit sequentie")
        d = data.count("D")
        e = data.count("E")
        r = data.count("R")
        k = data.count("K")
        print("Totaal D ",d)
        print("Totaal E ",e)
        print("Totaal R ",r)
        print("Totaal K ",k)
        print ("Totaal van de sequentie ",alles)

        if r+k > d+e: #Als de R en K bij elkaar opgeteld groter zijn dan de D en E bij elkaar opgeteld is het positief
            geladen = "postitief"
        elif r+k < d+e: #Als de R en K bij elkaar opgeteld kleiner zijn dan de D en E bij elkaar opgeteld is het negatief
            geladen = "negatief"
        else: #Anders is het neutraal
            geladen = "neutraal"
        print("Dit eiwit is bij een Ph van 7 ",geladen," geladen"+"\n")
        
    print("Voor het vergelijken van de eiwit sequentie en de RNA sequentie vul dan onderstaande iputs in")
    eiwit = input("\n"+"Wat is de eiwit sequentie ")
    DNA = input("\n"+"wat is de DNA sequentie ")

    lengte_dna = len(DNA)
    lengte_eiwit = len(eiwit)

    print ("\n"+"Het DNA is "+str(lengte_dna/lengte_eiwit)+" groter") # berekent de hoeveel keer groter het stuk eiwit is ten opzichte van het DNA
    print (" percetage van DE ",(d+e)/alles*100, "het percetage van RK is ",(r+k)/alles*100, "en het percetage van DERK is",(d+e+r+k)/alles*100)

    while True:
        answer = input('Run again? (y/n): ')
        if answer in ('y', 'n'):
            break
        print ('Invalid input.')
    if answer == 'y':
        continue
    else:
        print ('Goodbye')
        break

## WEEKTAAK 2
# Hier staan de gegevens + formules voor de "oude" organismen met ligase 1
mRNA_Ce = "ATGTTTTTCTCAAAAGCTGGCAAAGCCGCTGTTGAATGGGCAAAGGGTTCAAAAGTCCCTTACAAGGAGTTTGCTCTCACCCTTGAGAAAATCGAAGAGTTATCGGGAAAAAAGAAAGTGGATGAATTGGCTCAATTTTTCACCAAAGTTCTGGACTTTTCACCCGACGATTTAACAGCGTGCGTGTACATGTCAGTTAATCAGCTCGGGCCATCGTATGAAGGGCTCGAGCTTGGAGTTGCTGAAAATTCGCTGATCAAGGCTGTTGCTAAAGCGACCGGACGTACAGAGGGAAAAATTAAAGAAGATCTTCGCGCGAAAGGAGATCTTGGGACTGTCGCACAACAGTCAAGATCCAATCAGAAAATGCTTGCTGTTCCAAAAGCATTAACTGTTCCAACTGTTTTCAACAAGTTAACCGAAATTGCAAAGCTCAGTGGCACTTCAGCTATGAACAAGAAAGTTGATGCCATTAGTGCACTCCTCATTGCATGTCAAGGAATTGAGGCTCGATTCCTCGTCCGAATGCTCGCCGGCAAAATGAGAATCGGTCTCGGTGAACAAAGTGTTCTATCAGCACTTGGACATGCATTCACTCTTTCGAAAATAACTGATCAAAAGGTTCGTGGTGACAAACTCGATTCTCTGAAAGATGCAAATGTTAAGCGAGTAAAGACCGCCTATTGCGAATGCCCTAACTACAATCGTCTGATCGAAGTTGCACTGACTGAAGGTGTGGAAGCTCTTGTCGAAAAATGTAAACTTTCACCCGGAATTCCACTGAAACCTATGCTGGCTCACCCTACAAAGGGAATTGATGAAATTATGCGACGATTCAGAAATCAGACAATGACCTGTGAATGGAAATATGACGGAGAACGCGGCCAGATTCATAAACGAGAAGACGGGCAAATTTTCATCTACAGTCGAAACCAAGAGAACAACACTACCAAGTACCCCGATATTATCGAAAAAATTTCATCCTGCATCGGGGATGGGGTAACTTCATTTATTGTCGATGCTGAAGTTGTAGCTATCGATGAGGCTGGCTTAATTCTTCCGTTCCAAGTTTTGTCGACTCGTAAAAGGAAAAATGCAACTGATGATAACGGAGTCAAGGTTGTAGTTTTTCTTTTCGATCTTCTCTACTTCAATGGGGAGCCTCTCGTGAGAAAACCACTCCGAAAAAGAAGAGAACTTCTTCGAACAAACTTCAAAAAGATTGATGGAAGCTTCTATTTTGCAACTTCCGTAGATACAAATGATACTGATGAAATCAACTCTTTCTTCGATGAAGCCGTTCAAAATAAATGCGAAGGACTCATGATCAAAACTCTCGACACTGAAGCTACTTATGAGATTTCAAGACGTTCCCACAGCTGGTTGAAAATGAAGAAAGATTACGTTGATGGAGTAGGAGATACGTTGGATCTTGTCGTCATGGGTGCTTATTCTGGAGTTGGAAAGAGAACTGGAGTGTATGGAGGATATCTTCTCGGATGTTACAATCCTACTACAGAAGAGTACGAAAGTGTATGCAAGATTGGAACTGGTTTCACTGATGAAGATTTGGCCGAGCAATACAAGATCCTACAAGACAAGAAAATTGACAAATCTCCTTCTTATTATCAATTTGATCACACTCTTAAACCAGATGACACTTTTTCTCCGTATCTTGTTTTCGAAGTCAAATGTGCCGATATTACTATATCTCCGCGTCACAAAGCTGCAAGTGGATTGACGGATGATGGAAAAGGAATCTCTTTGAGATTTCCTCGTTTCCTGCGTATTCGGGACGATAAAAATTCCGACGATGCAACATCTTCGGAGCAAGTTCTTGAAATGTACAAAAACCAAGAAGCTTTTGCCAACCAGAAGATCGAAAAGGCGGATGCAGTTGATGAGGATGACGAATTTGAAGAAAAAGAAGATGAAGAGGAGGAGTTGAACATGACCAATGTATCTGAAGGAAGTTCTAAAGAAAATCCAGTGAAAGAGGAGATCAAGAAAGAGACTCCTAAATCAGTATCCCCGAAAAAATTCGAAAAGAAACCGCCTGTAAAATCTTCACCAGTTAACAAATCGCCCGTGAAAAGTTCACCAATAAAGAAAGAAGCAGAGAAAAAGAAAGGACCAGTTGCTAGCATCTTTTCATCATCGACAAAGAAGAATGAAAAAGACGTTAAAGTGGAATCTCCATCTCCGATCAGAAAGAAGAAGCTGCCTTCTGATTCTGACGAGTCTGATGAAGAAACCTCAACTAATAAGAAACAGCCAGCAAAGAAGAGGTCTCGCGTTGCAATTGATTCCGATTCCGACTAA"
mRNA_Xl = "GAGGGGAAACCTTCATTTTACGGCGGGGAGAAGGAGAGTGACCACTGACAGATAACAGCATCAGGAATCTTCTAACCATTCTTGACAAAATATGCAACGAACAATAAAGTCCTTTTTTCAGCCCAAGCTAGGGGCTGAAGTAAAGACTAAAGAAGAGAAAGTGAAGAATGATGTTCAAAAGGAAAAAGAAGAGCCAGAGAAAAGTGTTCCTGAACGTCCTTTAAAAGAGAGAAATGGCAGAGCTTTATGTGGAGATACCGAGTCACCAGTCAAACGAGTTTCAAAGAAGTCTGCACGTGTGTTGGAAAGTGATAGTGAAGAGGAAGAGGAGAATTCAAAGGTACAAGCGACTCCTGAAAAAATGAACAATGAAAGCGATCCAAAGAATGATGTTAAAGAAACTCCTCCGAGTGCACGTAAAGAAACTCCTCCGAGTGCACGTAAAGAAACTCCTCCGAGTGCACGTAAAGAAACTCCTCAGAGTGCACGTAAAGAAACTCCTCCGAGTGCACGTAAGGACGCAAAATCTGAAGGAGCTTCAGAGATGAACACTTCCCAAGATTTTGTCTCTCCTTGCAGCAGCAAATCTATTGACAGCCCTTTATGTTCAGATTCTCCTGGCATATCTCCTTCCGGTATCCCCAAACGAAAGACAGCCCGTAAACAGCTACCAAAGCGTAAACTGGAAATATCTCCCAGTGAATCAAATCCACCAAAAGATGATTTTGATGTCAAAGGAGCAGTGAAGCGACAAAAGAAAGAGGCAGAGGGAGATATTCAACAAGAAGAACCCATGGAGACAAGTCACAATATCTCCATGGAAGAGGAATGCCCCATAAAGAAAGAGACAAATCCCGACGTTGTTCAAGAAACCATATCCAACGCGGATGATCCAAACATAGAACTTGTAGACCAAAAGGATGTTGTTTCAGGAGAAAAGCAATCTGAGCCTAAATGTCAAGAGCAACCACAGCCCAAACTTACCAGTCCTACTGTGGAGCCTAAAGCTTCAAAAGGGAAGGCAAGAAAGAAAAACAGTCCTCTGCCAAAGAAAGTGAAATTTAGCGATAAAGTTTCTTTTAAAGACAATGACAGTGAGGAAAAAAGTAATGAGGAAAAAAGCGACGAGGAGCCTCAGAAGAAAGCAGATTCTGCTAAACCTGTGAAACAAATAAGCAGTTTCTTTGCCCCAAGGAAACCTGCAATAAAGACTGAAAAGAGAGAGGAAAATCTGAATGAAAAGAATGTCACTGAGACCTCTTTAGAAGAATCCCCTAAGCCTAAAAAAAACGTTGGCAGTTTCTTTGGAGCATCCAAGCAAGAAGCAACAGAAGAACAGACAGAGTATAACCCATCCAAGAGTAAATATCACCCCATAGATGATGCTTGCTGGTGTAATGGACAGAAGGTACCTTATCTTGCTGTTGCACGAACTTTTGAAAGGATAGAAGAGGAATCTGCCCGACTGAAGAACGTAGAGACTCTGAGTAATTTTCTGCGCTCCGTCATTGCTCTTACTCCTGAGGATCTCTTGCCTTGCATCTATCTTTGTCTGAACCGCCTGGGACCGGCATATGAAGGACTGGAGCTAGGCATAGGAGAAACTATTCTAATGAAAGCAGTTGCCCAGGCTACAGGACGCCAGCTTGAGAAGATAAAGGCTGAGGCACAAGAGAAAGGAGACCTTGGCCTGGTTGCTGAGAGCAGTCGTAGCAACCAACGCACAATGTTTACACCCCCAAAGCTCATGGCATCAGGTGTTTTCGGCAAGCTGAAAGATATAGCCAGGATGACTGGCAATGCTTCTATGAATAAGAAAATTGACATTATTAAAGGACTGTTTGTAGCCTGCAGGCATTCTGAGGCACGTTATATTGCCAGATCTCTTGGAGGAAAACTTAGAATTGGTCTTGCAGAACAGTCAGTGTTATCATCCATTGCTCAGGCAGTGTGCCTTACTCCTCCTGGGCGAGATGCCCCTCCTACTGTGATGGATGCCGGAAAGGGAATGAGTGCAGATGCCAGGAAATCCTGGATTGAGGAGAAAGCAATGATCTTGAAACAAACTTTTTGTGAGTTGCCAAACTATGATGCCATAATTCCTATTCTTTTGGAACATGGTATTGATGACCTCCCAAAACACTGCCGACTTACTCCAGGTATCCCTCTGAAACCAATGTTGGCGCATCCTACCAAGGGTATTGGGGAAGTGTTGAAGCGATTTGATGAAGCTGCCTTTACTTGTGAATACAAATATGACGGGGAGCGTGCACAGATACATATTCTGGAAAATGGGGAAGTACATGTATACAGCAGAAACCAAGAAAACAACACCACAAAATACCCTGACATCATCAGCAGAATTCCTAAGATTAAAAAAGAAAGCGTCAAATCCTGTATCCTCGATACGGAAGCTGTAGCCGGGGATGCAGAAAAGAAACAAATTCAGCCATTTCAAGTACTGACTACTAGAAAGAGAAAGGATGTGGATGCATCAGAGATTAAAGTGCAAGTTTGTGTGTATGCCTTTGACATGCTTTACCTTAATGGAGAGTCCCTAGTGAAGGAGCCATTTGCTAAGCGACGACAGCTCTTGAGAGACTCGTTCCTGGAGACTGAAGGGCAGTTCATGTTTGCTACATATATGGATAAGTCAAATACAGATGAAATTTCTGAGTTTCTTGATCAGTCTATTAAAGATTCATGTGAAGGACTTATGGTGAAGACACTGGAGCAAGACGCTACATATGAAATTGCAAAGAGATCTCACAATTGGTTAAAATTAAAGAAGGATTACTTGGAAGGTGTGGGTGATACTCTGGATCTTGTTGTTATTGGAGCTTACCTTGGGAAAGGGAAAAGAACTGGTATCTATGGAGGCTTCTTACTTGCGTCATACGACGAAGAAAGTGAGGAATATCAGACCATCTGCAAGATTGGAACAGGTTTTACAGATGACGACTTAGAAAAGCATTACAACTTCCTGAAGGATCATGTGATTGAAAATCCACGGAGCTACTACCGCTGGGACAGTGCCACAGAGCCAGATCACTGGTTTGATCCTGTACAAGTCTGGGAAGTTAAGTGTGCTGATCTATCCATTTCTCCAGTACATAAGGCAGCTCTTGGATTGGTGGAGGACCAGAAAGGAATTTCTCTGCGATTTCCTCGTTTTCTTCGTATCAGAGACGATAAGAAACCAGAGGAATCCACAAACAGTTTTCAGGTTGCAGATCTTTATAGAAAGCAGCAGCAAATCCAAAACACAAGTTCAACAGAGAAGGCAGAGGAGGATTTTTACTAGAATTACACATCAGCACTTTTATTTTATTTTTTTTCTCTTCTTTGTAATGTCCACATTGAACAATTGTGTTTTCAAGTCCAGGGGATTCAATTGGTATGTAAAGCAGCCATCAATAAGAAAGCCTTAGCTTGTATCCTATATATTACCATTCATTCTCTGAAGCATTTCAGGAAACCCCTCGATTCTGTCTCTACTGTCCATTTCTATGTTGACCTGAGAAACAAAAGTCATTGCCTAACCTCCCCCCACCTATTGTGTTGCCTTGGAGTAGTGAAGACGATGGAATTGGGCCTTTTTTTTTTTTTTTTTTGCTACATTGCTGATGTTGTTCTCTTCTATTTTATAACAGCTATGTGAACTAGACTTGTGAAATACTTGAAAAGCAATGGTTCTTCTTTACAATATT"
mRNA_Hs = "AGACGTCTGCGCGCGAATGCCGTGGCGCGAACTTGGGACTGCAGAGGCGCGCCTGGCGGATCTGAGTGTGTTGCCCGGGCAGCGGCGCGCGGGACCAACGCAAGGAGCAGCTGACAGACGAAGAAAAGTGCTGGACAGGAAGGGAGAATTCTGACGCCAACATGCAGCGAAGTATCATGTCATTTTTCCACCCCAAGAAAGAGGGTAAAGCAAAGAAGCCTGAGAAGGAGGCATCCAATAGCAGCAGAGAGACGGAGCCCCCTCCAAAGGCGGCACTGAAGGAGTGGAATGGAGTGGTGTCCGAGAGTGACTCTCCGGTGAAGAGGCCAGGGAGGAAGGCGGCCCGGGTCCTGGGCAGCGAAGGGGAAGAGGAGGATGAAGCCCTTAGCCCTGCTAAAGGCCAGAAGCCTGCCCTGGACTGCTCACAGGTCTCCCCGCCCCGTCCTGCCACATCTCCTGAGAACAATGCTTCCCTCTCTGACACCTCTCCCATGGACAGTTCCCCATCAGGGATTCCGAAGCGTCGCACAGCTCGGAAGCAGCTCCCGAAACGGACCATTCAGGAAGTCCTGGAAGAGCAGAGTGAGGACGAGGACAGAGAAGCCAAGAGGAAGAAGGAGGAGGAAGAAGAGGAGACCCCGAAAGAAAGCCTCACAGAGGCTGAAGTGGCCACAGAGAAGGAAGGAGAAGACGGGGACCAGCCCACCACGCCTCCCAAGCCCCTAAAGACCTCCAAAGCAGAGACCCCGACGGAAAGCGTTTCAGAGCCTGAGGTGGCCACGAAGCAGGAACTGCAGGAGGAGGAAGAGCAGACCAAGCCTCCCCGCAGAGCTCCCAAGACGCTCAGCAGCTTCTTCACCCCCCGGAAGCCAGCAGTCAAAAAAGAAGTGAAGGAAGAGGAGCCAGGGGCTCCAGGAAAGGAGGGAGCTGCTGAGGGACCCCTGGATCCATCTGGTTACAATCCTGCCAAGAACAACTATCATCCCGTGGAAGATGCCTGCTGGAAACCGGGCCAGAAGGTTCCTTACCTGGCTGTGGCCCGGACGTTTGAGAAGATCGAGGAGGTGTCTGCTCGGCTCCGGATGGTGGAGACGCTGAGCAACTTGCTGCGCTCCGTGGTGGCCCTGTCGCCTCCAGACCTCCTCCCTGTCCTCTACCTCAGCCTCAACCACCTTGGGCCACCCCAGCAGGGCCTGGAGCTTGGCGTGGGTGATGGTGTCCTTCTCAAGGCAGTGGCCCAGGCCACAGGTCGGCAGCTGGAGTCCGTCCGGGCTGAGGCAGCCGAGAAAGGCGACGTGGGGCTGGTGGCCGAGAACAGCCGCAGCACCCAGAGGCTCATGCTGCCACCACCTCCGCTCACTGCCTCCGGGGTCTTCAGCAAGTTCCGCGACATCGCCAGGCTCACTGGCAGTGCTTCCACAGCCAAGAAGATAGACATCATCAAAGGCCTCTTTGTGGCCTGCCGCCACTCAGAAGCCCGGTTCATCGCTAGGTCCCTGAGCGGACGGCTGCGCCTTGGGCTGGCAGAGCAGTCGGTGCTGGCTGCCCTCTCCCAGGCAGTGAGCCTCACGCCCCCGGGCCAAGAATTCCCACCAGCCATGGTGGATGCTGGGAAGGGCAAGACAGCAGAGGCCAGAAAGACGTGGCTGGAGGAGCAAGGCATGATCCTGAAGCAGACGTTCTGCGAGGTTCCCGACCTGGACCGAATTATCCCCGTGCTGCTGGAGCACGGCCTGGAACGTCTCCCGGAGCACTGCAAGCTGAGCCCAGGGATTCCCCTGAAACCAATGTTGGCCCATCCCACCCGGGGCATCAGCGAGGTCCTGAAACGCTTTGAGGAGGCAGCTTTCACCTGCGAATACAAATATGACGGGCAGAGGGCACAGATCCACGCCCTGGAAGGCGGGGAGGTGAAGATCTTCAGCAGGAATCAGGAAGACAACACTGGGAAGTACCCGGACATCATCAGCCGCATCCCCAAGATTAAACTCCCATCGGTCACATCCTTCATCCTGGACACCGAAGCCGTGGCTTGGGACCGGGAAAAGAAGCAGATCCAGCCATTCCAAGTGCTCACCACCCGCAAACGCAAGGAGGTGGATGCGTCTGAGATCCAGGTGCAGGTGTGTTTGTACGCCTTCGACCTCATCTACCTCAATGGAGAGTCCCTGGTACGTGAGCCCCTTTCCCGGCGCCGGCAGCTGCTCCGGGAGAACTTTGTGGAGACAGAGGGCGAGTTTGTCTTCGCCACCTCCCTGGACACCAAGGACATCGAGCAGATCGCCGAGTTCCTGGAGCAGTCAGTGAAAGACTCCTGCGAGGGGCTGATGGTGAAGACCCTGGATGTTGATGCCACCTACGAGATCGCCAAGAGATCGCACAACTGGCTCAAGCTGAAGAAGGACTACCTTGATGGCGTGGGTGACACCCTGGACCTGGTGGTGATCGGCGCCTACCTGGGCCGGGGGAAGCGGGCCGGCCGGTACGGGGGCTTCCTGCTGGCCTCCTACGACGAGGACAGTGAGGAGCTGCAGGCCATATGCAAGCTTGGAACTGGCTTCAGTGATGAGGAGCTGGAGGAGCATCACCAGAGCCTCAAGGCGCTGGTGCTGCCCAGCCCACGCCCTTACGTGCGGATAGATGGCGCTGTGATTCCCGACCACTGGCTGGACCCCAGCGCTGTGTGGGAGGTGAAGTGCGCTGACCTCTCCCTCTCTCCCATCTACCCTGCTGCGCGGGGCCTGGTGGATAGTGACAAGGGCATCTCCCTTCGCTTCCCTCGGTTTATTCGAGTCCGTGAAGACAAGCAGCCGGAGCAGGCCACCACCAGTGCTCAGGTGGCCTGTTTGTACCGGAAGCAAAGTCAGATTCAGAACCAACAAGGCGAGGACTCAGGCTCTGACCCTGAAGATACCTACTAAGCCCTCGCCCTCCTAGGGCCTGGGTACAGGGCATGAGTTGGACGGACCCCAGGGTTATTATTGCCTTTGCTTTTTAGCAAATCTGCTGTGGCAGGCTGTGGATTTTGAGAGTCAGGGGAGGGGTGTGTGTGTGAGGGGGTGGCTTACTCCGGAGTCTGGGATTCATCCCGTCATTTCTTTCAATAAATAATTATTGGATAGCTA"
mRNA_Dd = "ATGCAATCTTCTATGTGGTAATTAGAATTTTTTTATTTTATTTTATTTTTTAATTACTTTAAAGCTAACTCGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTAAAAAAAATTAATTAATTTGACATAATATATTATAGGAGTTTCTTACAAAAGAAAGAAGGTGGAGAAATTGAAGATATAGAAAAGAAAATTAGTAATGCACAAGAATTAAATAAACTTAAAACTTCCCCTAAAAAGAAAAGAGAAGCAGTGGTTAAAGAAAAAGTTGAAAAGAAAGAAAAAAAAGAAACAAAACCAAAGAGAAAGAGTTCAAAAAAAAATAAGGAAGAAGAAGAAGAAGAAGAACAAGAAGAACAAGATGGTGAAGAAGAACAAGAAGAAGAAGAAGAATATCAACAACAAGATGAAGAAATTGAAGAAGATATAAATGGTGAAGAAGAAATGGAATTAGATGAAAATGAAAAAGAAAAGAATAAAAAGAAAAAACAATCATTAAAAACTAAAGAAAATAAAGAATCAAAATCATCATCTTCTTCAAAGAAAACAATAGAAAATAAAGAAACTAAAAAACCTGAAAAACAATCTTCAAAACAATCAAATAATTTGAAAAGATTAAAAAGAAAGAAAATGGATGACGATGAAGAAGACGAAGAAGATGAAAATAAAACTGATGATAATGATTTAGATGATATGCTCGATGATGATAGTGATAATGAAAAAGATTCAATTTCTTCAAAAGATAAAGAGTATAAAGAAAAAGTTTTAAAAGATAAAGAGAAAAAAGAAAAAGAAAAGAAAGAAAAAGAGTTAAAAGAAAAAGAATCAAAGGAAAAAGAAAAGAAAGAAAAAGAAAAAAAAGAAAAAGAAGAAAAAGATAAAAAAGAAAAGGAATTAAAAGAAAAGGAATTAAAAGAAAAGGAATTAAAAGATAAAAAAGAAAAGGAGCTAAAAGAAAAAGAAAAAGAACTCAAAGATAAAGAGAAAAAAGAAAAAGAGTTAAAAGAAAAAGAGAAAAAAGAAAAGGAAGAAAAGGAAAAGGAGAAAAAAGAGAAAAAAGAAAAAGAATTGAAAGAAAAAGAAGAAAAAGAGAAAAAAGAAAAGGAATTAAAAGAAAAGGAATTAAAAGAAAAGGAATTAAAAGAAAAGGAATTAAAAGAAAAGGAATTAACTTCACCAAAAAAAGAAACTATTGATATTTCAGATTTATTTAAAAGAGCAAATGCTGAAGCTAAATCGTCAGTACCAACCTCAACATCTAAAAACAGTAAAACTAATAAAAAACAAAAAGTTGATCATAAACCAACAGCAACAACAAAAAAACCATCACCTGTACTTGAAGCAAAGCAAAGCACCACAACCACCACCACCACAACTACTACCTCTACCGCCACAACTATTTCTTCAAAATCAATTTCAAGTCCATCTAAAAAAGAAGAAAAAGAAGTAATAACTTCAAAAAAACAAGTTGAAGCAACAAAAGTAGAAGTTAAAAAAGAAAAAGAAAAAGAAAAAGAAAAAGAAAAAGAAGATGATGAGGAAGAAGAGGAAGAAGAAGAAGATGATGATGAAAAATTAGAAGATATTGATGAGGAAGAATATGAAGAAGAAGAAGAAGAAGATGAAGAGGGAATTAGTGAAAATGAAGAAGAAGAAGAAAAGAAAAGTACACAAATTAAAAGTAAATTTATTAAAAAAGTACCAATTTCAAAAAAGAAAGGTAATGCAAAAACTATTCAAGCTGATTTAAAGGTTATTGGAAAATATAGACCAATTGAGGATGCACAATGGAAAAAAGGTGAAGCTGTACCATATATGGTATTAGCAAAAACCTTTGAAATGATGGAATCAACATCATCAAGATTAATTATTATTGAACATTTAGCCAATTTATTTAGATCGATTATGTTATTATCACCAAAGGATTTGGTTATGACAATTTATTTATCAATCAATAAGATTGGTCCATCCTATCAATCTAAAGAGTTGGGTATTGGTGAACATGTTTTAATTAAATCATTAGCAGAGTCCACTGGTAGATCAGTGGATGTTATTAAACAAGAGTTGACAGAGGTTGGTGATTTGGGTATAATTGCACAAAATAGTAGATCCACTCAAACTCTAATGGGTAAACCAACACCATTGACCATTCAATCGGTGTTCAAAACATTTCAACAAATTGCTGATCTCTCTGGCACAGGTGGCCAACAAAAAAAGAAAGATCTTATAAAGAAACTATTGGTATCATGTAAAGATTGTGAAACACTTTATATCATTCGTTCATTGCAAGGTAAGCTTAGAATTGGTCTAGCCGAACGTTCAGTATTGATGGCATTGGCTAAATCCGTATTGGTAACACCACCAATTGATGGTAGCGGTCAACAGATATTTGATATTAGAAAACAAATGAAACAAGAGGAATTTGAAGAACGTTATCAAAATGTTGTATCAAAGGTAACTCGTGCATATAGTCAGTTACCAAATTATGATTTATTTGTACCTCATTTAATTGCTGTGAATGGTATTGATAATATTTTGAGTACATGTTCATTGAAAGTTGGTATTCCAGTGAAACCAATGTTAGCACAACCAACCACTGGTATCAGTCAAATGTTGGATCGTTTCTCTGATATGGAGTTTACTTGTGAATTCAAATATGATGGTGAACGTGCTCAAATCCATCGTTTACCAGATGGTACCACTCATATTTATACCAGAAATTTAGAGGATTACACTCAAAAATATCCAGATATTGTTGCAAATGTTACTAAATTCGTTGGGCCAAATGTGAAATCATTCATTTTAGATTGTGAAGCAGTTGCATTTGATGCTGCAACAAAAAAGATTTTATCATTTCAAGTTTTATCGACTAGAGCAAGAAAAAGTGTACAATTGTCACAAATTAAAGTACCAGTTTGTGTATTTGCTTTCGATTTACTCTATTTGAATGGTCAATCATTAATTGATGAACCATTAATCAAACGTCGTGAACATTTAGTTGAAAATTTCATTGCATCCGATGGTGTATTTGCTTTTGCTAAATATTCAAATATTTCCGACGTAAATGATATTCAATCCTATCTTGAAGAGGCTGTCGAGGGTAATTGTGAAGGTTTAATGGTGAAAACTTTGAAAGAGAAATCAATCTATGAACCATCACGTCGTTCTTACAATTGGTTAAAGATTAAAAAAGATTATATGCAAGGTATGACCGATAGTTTAGATTTGGTACCCATTGGTGCATGGTATGGTAAAGGTAAAAGAACAGGTACTTATGGTGCTTACTTGTTGGCTTGTTATGATGAAAACAATGAAGAATTCCAAACACTCTGTAAGATTGGTACTGGTTTCTCTGATGAACAATTGACTACTTTTACCAGTCAATTGAAACCTCATCTAATTAATCAACCACGTAATCAATTCCGTTTCTCTGATTCAATTAAACCTGATGTTTGGTTCTCTCCAAGTTGTGTTTGGGAGGTATTGGCCGCTGATTTATCAATCTCTCCAGTTCATACAGCTGCATCTGGTATTTTGGATCCAAATAAAGGTATCGCTTTACGTTTCCCACGTTTCATTAGAATTCGTCCTGATAAATCTCCTGAAGATGCAACTAGTTCTGATCAAGTTGTTGATATGTATCAAAATCAAAAAATTAATAGTCAATCTTCAAAAATTAATGAAAAAGATGAAGATTATTAA"
mRNA_At = "CCTAATTTGGCCCAACATAAAGGAGAGAGTGGCGGGTGAGAAATTCTGCCGCCAATATATTATCACCTTTCTTCAAGGTTGCAAACTTGCAACACCTGTCCTTTCTAAAACCCTAATTTCAAAATCGACTGATGTTAGCGATTCGATCGTCGAATTACCTCCGATGCATACCTTCTCTCTGTACTAAAACCCAAATCTCTCAATTCTCCTCCGTGTTAATCTCTTTTAGCCGCCAAATTTCCCACTTGCGTCTTAGCTCGTGCCATAGAGCCATGTCTTCTTCCCGCCCTTCTGCATTTGATGCTCTCATGTCCAATGCTCGTGCAGCCGCCAAGAAGAAGACTCCCCAGACAACTAATTTGTCTCGCTCGCCGAACAAAAGGAAAATTGGAGAAACCCAAGATGCTAATTTGGGCAAAACTATTGTTTCCGAAGGTACACTTCCAAAAACGGAGGATCTGCTGGAGCCTGTTTCTGATTCTGCAAATCCCAGATCGGATACATCGTCAATTGCGGAGGATTCAAAGACGGGAGCGAAAAAGGCTAAGACTTTGAGCAAGACAGACGAAATGAAGAGCAAAATTGGATTGCTGAAGAAGAAGCCGAATGATTTCGATCCTGAAAAAATGTCTTGCTGGGAGAAAGGGGAGAGAGTTCCGTTTCTGTTTGTCGCATTGGCTTTTGATCTGATCTCAAATGAAAGTGGCCGGATTGTGATTACTGATATTCTGTGTAACATGTTGAGAACTGTTATTGCCACTACTCCTGAGGATTTGGTCGCTACTGTTTATCTTTCGGCGAATGAGATTGCCCCGGCTCATGAAGGTGTAGAATTGGGAATTGGTGAGAGTACAATTATCAAGGCTATCTCTGAGGCTTTTGGTAGAACTGAGGATCATGTTAAGAAGCAGAATACGGAACTGGGAGACTTGGGACTTGTAGCAAAAGGAAGCCGTTCGACTCAGACTATGATGTTCAAGCCCGAACCATTGACTGTTGTCAAGGTTTTCGATACGTTTCGACAAATTGCTAAGGAAAGTGGAAAAGATAGTAATGAAAAGAAGAAGAATCGAATGAAGGCACTTCTTGTGGCGACAACAGACTGTGAACCTCTTTACTTAACACGATTACTTCAGGCAAAATTGCGGTTAGGGTTCTCAGGTCAGACTGTCTTAGCCGCATTGGGACAAGCCGCTGTATATAATGAAGAGCACTCAAAGCCACCCCCAAATACCAAGTCTCCTTTAGAAGAGGCTGCAAAGATTGTTAAACAAGTATTCACTGTACTTCCTGTCTATGACATTATTGTTCCTGCTCTTCTAAGTGGCGGTGTGTGGAATCTTCCAAAAACTTGTAACTTTACATTGGGTGTTCCAATTGGACCCATGCTTGCAAAACCAACCAAAGGTGTAGCTGAGATACTGAATAAATTCCAGGACATCGTTTTCACATGTGAATACAAATATGATGGGGAACGTGCACAGATACATTTTATGGAGGATGGTACATTTGAGATATACAGTCGAAATGCTGAAAGAAACACTGGGAAGTACCCGGATGTTGCTCTTGCGTTATCAAGATTAAAGAAGCCTTCTGTGAAATCTTTTATTCTGGATTGTGAAGTTGTTGCTTTCGACAGGGAGAAAAAGAAAATTCTTCCGTTCCAGATTTTGAGCACTCGAGCCCGTAAAAATGTGAATGTCAATGATATCAAGGTTGGCGTATGCATCTTTGCTTTTGACATGTTATATCTAAATGGCCAACAACTTATCCAGGAGAATCTTAAAATTCGCCGAGAGAAGCTATACGAATCATTTGAGGAAGATCCTGGGTATTTCCAGTTTGCAACTGCTGTAACATCTAACGATATCGATGAAATACAAAAGTTTCTTGACGCTTCTGTTGATGTTGGCTGCGAAGGTTTAATCATTAAAACATTGGACTCAGATGCTACCTATGAGCCTGCAAAGCGATCAAATAATTGGCTAAAACTGAAGAAAGACTATATGGACAGCATTGGGGACTCTGTGGATCTTGTACCAATTGCTGCTTTCCATGGACGTGGAAAACGCACAGGTGTCTATGGTGCATTTTTACTCGCTTGCTATGATGTTGATAAGGAAGAGTTCCAGAGCATTTGTAAAATTGGTACTGGATTTTCTGATGCCATGCTTGACGAGCGGTCGTCCAGTCTTCGCTCTCAAGTGATTGCTACTCCAAAACAATACTACCGAGTTGGAGACAGCCTCAATCCAGATGTTTGGTTTGAGCCCACTGAGGTCTGGGAAGTGAAAGCAGCTGACTTAACAATTAGCCCTGTGCACCGTGCAGCTACTGGCATAGTGGATCCTGATAAGGGGATTTCTCTTCGTTTTCCTCGTCTACTTCGTGTACGGGAAGACAAGAAGCCCGAGGAAGCAACATCATCTGAGCAGATTGCTGATTTGTACCAAGCTCAGAAACACAATCATCCAAGTAATGAAGTCAAAGGTGACGATGATTGAACAACAGTAATCTGGCCTCAGAGCACATTTCCTCGTATGTACGACATTGCTCGTAACTTGCTAATGATGCACATTGCGTGTTTGAGTTTTCAACTGTAACTGCTTATGTAAAACTGCTTTTAGGAAAAGTGAATGAAAGGTTCTGGAAAAAAATTGGTACACTCATCAACTGACTCTGGAATGAATAAAAACACTGCCCTGATTGACATCACTGAGCTATCTATGATTGGCAGAAATGTGGAATATGTTT"
c = "C"
g = "G"
GC_mRNA_Dd = 100/len(mRNA_Dd)*(mRNA_Dd.count(c)+mRNA_Dd.count(g)) # datab. GC% = 22.46
GC_mRNA_Hs = 100/len(mRNA_Hs)*(mRNA_Hs.count(c)+mRNA_Hs.count(g)) # datab. GC% = 40.9
GC_mRNA_Xl = 100/len(mRNA_Xl)*(mRNA_Xl.count(c)+mRNA_Xl.count(g)) # datab. GC% = 40.2325
GC_mRNA_At = 100/len(mRNA_At)*(mRNA_At.count(c)+mRNA_At.count(g)) # datab. GC% = 36.9
GC_mRNA_Ce = 100/len(mRNA_Ce)*(mRNA_Ce.count(c)+mRNA_Ce.count(g)) # datab. GC% = 35.4342
# Hier begint het script voor de interactiviteit (als er #hier bijstaat = nog onder constructie)
print ("Hai. I calculate the GC% of mRNA form an organism."
       " I have five different organisms ready for you.")
q1 = input("Do you want to know the GC% of one of these organisms?"
           " Or do you want me to calculate a new one? (old/new): ")
if q1 == "new":
    name_organism = input.__call__("What is the name of the organism? ")
    mRNA_organism = input.__call__("Put the mRNA sequence here (without enters!): ")
    GC_mRNA_organism = 100/len(mRNA_organism)*(mRNA_organism.count(c)+mRNA_organism.count(g))
    print ("The GC% for", name_organism, "is", GC_mRNA_organism)
    quit
elif q1 == "old":
    print("Alright. Choose an organism:" #Zoek uit hoe je hier een enter kan toevoegen
          "- Caenorhabditis elegans (Ce)"
          "- Dictyostelium discoideum (Dd)"
          "- Homo sapiens (Hs)"
          "- Xenopus laevis (Xl)"
          "- Arabidopsis thalia (At)")
    old = input("(Don't forget the capslock on the first letter!): ") #Zin aanpassen
    if old == "Ce":
        print ("The GC% for Caenorhabditis elegans is 35.4342")
        print ("The GC% on ligase 1 is", GC_mRNA_Ce)
        quit
    elif old == "Dd":
        print ("The GC% for Dictyostelium discoideum is 22.46")
        print ("The GC% on ligase 1 is", GC_mRNA_Dd)
        quit
    elif old == "Hs":
       print ("The GC% for Homo sapiens is 40.9")
       print ("The GC% on ligase 1 is", GC_mRNA_Hs)
       quit
    elif old == "Xl":
        print ("The GC% for Xenopus laevis is 40.2325")
        print ("The GC% on ligase 1 is", GC_mRNA_Xl)
        quit
    elif old == "At":
        print ("The GC% for Arabidopsis thalia is 36.9")
        print ("The GC% on ligase 1 is", GC_mRNA_At)
        quit
    else:
        print ("Sorry, I do not understand. Quitting.")
        quit
else:
    print("Sorry, I do not understand. Quitting.")
    quit


## WEEKTAAK 4
#24-09-19
#Auteur David van Eersel
#Berekent de totale massa van een eiwit sequentie
#massa in Da
#Bron: http://education.expasy.org/student_projects/isotopident/htdocs/aa-list.html

a = 71.0788
r = 156.1875
n = 114.1038
d = 115.0886
c = 103.1388
e = 129.1155
q = 128.1307
g = 57.0519
h = 137.1411
i = 113.1594
l = 113.1594
k = 128.1741
m = 131.1926
f = 147.1766
p = 97.1167
s = 87.0782
t = 101.1051
w = 186.2132
y = 163.1760
v = 99.1326

#invullen van de sequentie
eiwit = input("Wat is de eiwitsequentie? ")

#telt de aminozuren 
A = eiwit.count("A")
R = eiwit.count("R")
N = eiwit.count("N")
D = eiwit.count("D")
C = eiwit.count("C")
E = eiwit.count("E")
Q = eiwit.count("Q")
G = eiwit.count("G")
H = eiwit.count("H")
I = eiwit.count("I")
L = eiwit.count("L")
K = eiwit.count("K")
M = eiwit.count("M")
F = eiwit.count("F")
P = eiwit.count("P")
S = eiwit.count("S")
T = eiwit.count("T")
W = eiwit.count("W")
Y = eiwit.count("Y")
V = eiwit.count("V")

#berekent de totale massa van de eiwitsequentie
massa = (A*a)+(R*r)+(N*n)+(D*d)+(C*c)+(E*e)+(Q*q)+(G*g)+(H*h)+(I*i)+(L*l)+(K*k)+(M*m)+(F*f)+(P*p)+(S*s)+(T*t)+(W*w)+(Y*y)+(V*v)

print("De massa van het eiwit is", massa, "Da.")

## WEEKTAAK 5
#Auteur: Teun van Dorp
#Datum: 2/10/2019
#berekent hoeveel van de aminozuren hetzelde zijn

#input van de eiwitsequenties
eiwit1 = input("Wat is de eerste eiwitsequentie? ")
eiwit2 = input("Wat is de tweede eiwitsequentie? ")

#lengte van de eiwitsequenties
len1 = len(eiwit1)
len2 = len(eiwit2)
tel = 0

#lengte van eiwitsequenties printen
print("Eiwit 1 is", len1, "lang", "\n" + "Eiwit 2 is", len2, "lang")

#kijken welke sequentie langer is en vervolgens in lenlang/lenklein zetten
if len1 < len2:
    lenlang = len2
    lenklein = len1
else:
    lenlang = len1
    lenklein = len2

#kijken op welke locaties de letters hetzelfde zijn en hoevaak dat is
for plaats in range(lenklein):
    if eiwit1[plaats] == eiwit2[plaats]:
        tel += 1

#print het percentage dat hetzelde is
print("Aantal gelijke letters:", tel)
print("De sequenties zijn voor", tel/lenlang*100, "% gelijk.")
